// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW3FX0dBGTckHFMnyhzjQaMCCO1QYP0es',
    appId: '1:675064889819:web:10624a94b97102ede1a7fe',
    messagingSenderId: '675064889819',
    projectId: 'melody-a87c2',
    authDomain: 'melody-a87c2.firebaseapp.com',
    storageBucket: 'melody-a87c2.firebasestorage.app',
    measurementId: 'G-ES8DTW0B06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9CNeTf7-Pxf2lczXK8sYclYKMEQXJRO4',
    appId: '1:675064889819:android:158bdfdc8b795cb5e1a7fe',
    messagingSenderId: '675064889819',
    projectId: 'melody-a87c2',
    storageBucket: 'melody-a87c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvRmiUYB8glNLlTTefJBoaCkFuFumGJz8',
    appId: '1:675064889819:ios:892ab7b7abf1ff9ee1a7fe',
    messagingSenderId: '675064889819',
    projectId: 'melody-a87c2',
    storageBucket: 'melody-a87c2.firebasestorage.app',
    iosBundleId: 'com.example.melody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvRmiUYB8glNLlTTefJBoaCkFuFumGJz8',
    appId: '1:675064889819:ios:892ab7b7abf1ff9ee1a7fe',
    messagingSenderId: '675064889819',
    projectId: 'melody-a87c2',
    storageBucket: 'melody-a87c2.firebasestorage.app',
    iosBundleId: 'com.example.melody',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW3FX0dBGTckHFMnyhzjQaMCCO1QYP0es',
    appId: '1:675064889819:web:fe2154d7d0e9da4de1a7fe',
    messagingSenderId: '675064889819',
    projectId: 'melody-a87c2',
    authDomain: 'melody-a87c2.firebaseapp.com',
    storageBucket: 'melody-a87c2.firebasestorage.app',
    measurementId: 'G-7P1CPJXWZ6',
  );
}
